import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Copy, Check, Download, ExternalLink, RefreshCw } from 'lucide-react';
import './ReportViewer.css';

/**
 * Report Viewer Component
 * Renders the markdown report generated by the agents
 */
export default function ReportViewer({ result, onNewSearch }) {
    const [copied, setCopied] = React.useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(result.report);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const element = document.createElement("a");
        const file = new Blob([result.report], { type: 'text/markdown' });
        element.href = URL.createObjectURL(file);
        element.download = `research-${result.query.slice(0, 30).replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    };

    if (!result) return null;

    return (
        <div className="report-container animate-fade-in">
            <div className="report-header glass-panel">
                <div className="report-meta">
                    <h2 className="report-query">{result.query}</h2>
                    <div className="report-stats">
                        <span className="stat-badge">
                            <ExternalLink size={14} />
                            {result.num_sources} Sources Analyzed
                        </span>
                        <span className="stat-badge">
                            <RefreshCw size={14} />
                            {result.execution_time?.toFixed(1) || 'N/A'}s Execution
                        </span>
                    </div>
                </div>

                <div className="report-actions">
                    <button onClick={handleCopy} className="action-btn" title="Copy Markdown">
                        {copied ? <Check size={18} className="text-success" /> : <Copy size={18} />}
                    </button>
                    <button onClick={handleDownload} className="action-btn" title="Download Markdown">
                        <Download size={18} />
                    </button>
                    <button onClick={onNewSearch} className="primary-btn">
                        New Research
                    </button>
                </div>
            </div>

            <div className="report-content glass-panel">
                <div className="markdown-body">
                    <ReactMarkdown
                        components={{
                            a: ({ node, ...props }) => (
                                <a {...props} target="_blank" rel="noopener noreferrer" />
                            )
                        }}
                    >
                        {result.report}
                    </ReactMarkdown>
                </div>
            </div>
        </div>
    );
}
